import streamlit as st
import pandas as pd
import requests
import time
from datetime import datetime
import io

st.title("IP Blacklist Lookup Demo")
st.write("Upload an Excel file with IP addresses to get Blacklist Status, Detection Count, Country, and ISP.")

# HetrixTools API key (team must get their own free key)
HETRIX_API_KEY = "835fa8243d3a64c62462a5e4bc48a93a"  # Replace with key from hetrixtools.com

def get_blacklist_status(ip):
    try:
            url = f"https://api.hetrixtools.com/v2/{HETRIX_API_KEY}/blacklist-check/ipv4/{ip.strip()}/"
                    response = requests.get(url, timeout=5)
                            data = response.json()
                                    if data["status"] == "success":
                                                blacklist_count = len(data["blacklisted_on"])
                                                            return {
                                                                                "Blacklist Status": "Blacklisted" if blacklist_count > 0 else "Not Blacklisted",
                                                                                                "Detection Count": blacklist_count
                                                            }
                                                                    return {"Blacklist Status": "Failed", "Detection Count": 0}
                                                                        except:
                                                                                return {"Blacklist Status": "Error", "Detection Count": 0}

                                                                                def get_ip_info(ip):
                                                                                    try:
                                                                                            url = f"http://ip-api.com/json/{ip.strip()}"
                                                                                                    response = requests.get(url, timeout=5)
                                                                                                            data = response.json()
                                                                                                                    return {
                                                                                                                                    "Country": data.get("country", "Unknown") if data["status"] == "success" else "Failed",
                                                                                                                                                "ISP": data.get("isp", "Unknown") if data["status"] == "success" else "Failed"
                                                                                                                    }
                                                                                                                        except:
                                                                                                                                return {"Country": "Error", "ISP": "Error"}

                                                                                                                                # File uploader
                                                                                                                                uploaded_file = st.file_uploader("Choose an Excel file", type=["xlsx"])

                                                                                                                                if uploaded_file is not None:
                                                                                                                                    try:
                                                                                                                                            # Read Excel
                                                                                                                                                    df = pd.read_excel(uploaded_file)
                                                                                                                                                            ip_column = "IP" if "IP" in df.columns else df.columns[0]
                                                                                                                                                                    ip_list = df[ip_column].dropna().unique()

                                                                                                                                                                            if len(ip_list) == 0:
                                                                                                                                                                                        st.error("No valid IP addresses found.")
                                                                                                                                                                                                else:
                                                                                                                                                                                                            st.write(f"Found {len(ip_list)} unique IPs. Click below to process.")

                                                                                                                                                                                                                        # Process button
                                                                                                                                                                                                                                    if st.button("Process IPs"):
                                                                                                                                                                                                                                                    with st.spinner("Processing..."):
                                                                                                                                                                                                                                                                        results = []
                                                                                                                                                                                                                                                                                            ipapi_count = 0

                                                                                                                                                                                                                                                                                                                for ip in ip_list:
                                                                                                                                                                                                                                                                                                                                        # Respect ip-api.com rate limit (45/min)
                                                                                                                                                                                                                                                                                                                                                                if ipapi_count >= 40:
                                                                                                                                                                                                                                                                                                                                                                                            time.sleep(70)
                                                                                                                                                                                                                                                                                                                                                                                                                        ipapi_count = 0

                                                                                                                                                                                                                                                                                                                                                                                                                                                blacklist_data = get_blacklist_status(ip)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ip_data = get_ip_info(ip)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "IP": ip,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Country": ip_data["Country"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "ISP": ip_data["ISP"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Blacklist Status": blacklist_data["Blacklist Status"],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Detection Count": blacklist_data["Detection Count"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ipapi_count += 1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Create DataFrame
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                results_df = pd.DataFrame(results)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    st.write("Results:")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        st.dataframe(results_df)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # CSV download
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                csv_buffer = io.StringIO()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results_df.to_csv(csv_buffer, index=False)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        csv_data = csv_buffer.getvalue()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                st.download_button(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            label="Download CSV",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data=csv_data,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            file_name=f"ip_blacklist_results_{timestamp}.csv",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mime="text/csv"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.error(f"Error processing file: {e}")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            st.write("Note: Blacklist status uses HetrixTools (free, 5,000 queries/month). For ipvoid.com's full detection count, a paid API like APIVoid may be needed.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                    }
                                                            }